[package]

name = "opencl-raytrace"
version = "0.0.0"
authors = []

[[bin]]

name = "raytrace"
path = "./src/bin.rs"

[dependencies]
cgmath = "*"
glium = "*"
glutin = "*"
log = "*"
rand = "*"
time = "*"

[dependencies.ocl]
git = "https://github.com/cogciprocate/ocl"
